### ISSUE TITLE
Leave ResizeObserver polyfilling to userland

### ISSUE THREAD

**Issue by donysukardi** [react-spring/react-use-measure#6]
Currently the ResizeObserver polyfill takes up 80% of the entire package size - https://bundlephobia.com/result?p=react-use-measure@1.1.2.

I think it'd be good to leave the polyfilling to the library users (with recommendation) as there are a few options that each comes with pro and cons.

Some devs prefer polyfilling on-demand using services like http://polyfill.io/ and https://github.com/wessberg/polyfiller that only load the polyfill for platforms that require it.

**Comment by drcmda** [comment]
i was going back and forth with this, but doesn't the lack of RO in safari make it essentially futile? that means a huge segment of desktop users and all ios users are left out.

the polyfill we're using can also be loaded async: https://github.com/juggle/resize-observer#switching-between-native-and-polyfilled-versions it wouldn't be part of the bundle unless it's needed.

**Comment by everweij** [comment]
Yeah, I've been struggling with this as well. It's a tradeoff between 'it just works' vs. control.

Pros of integrating polyfill:
- It just works
- User gets more control of when and how to use the polyfill

Cons of integrating polyfill
- User may have to take an extra step. Note: Sometimes this step is not necessary, since the user needed the polyfill for another lib already for example
- We're basically taking responsibility for the hook working cross-browser (something that is not 100% under our control)
- User may end up with different versions of the ResizeObserver polyfill
- Some users may not need the polyfill at all. I know that's rare right now (Safari), but it does affect the bundle size, and it's not really easy to get rid of it.

I may have forgotten a few points.
Personally, I think we should leave the responsibility to the user, and make the user aware of this and help them by providing recommendations in the readme.

In react-laag, i'm letting the user optionally inject a polyfill via props. I do this because most polyfill's advice you not to affect the window object. What do you think is wise?

**Comment by drcmda** [comment]
alright then. i'll put it back. this is a breaking change unfortunately. do we want to throw some other unresolved business into a new major release?

**Comment by everweij** [comment]
What do you think about this relatively small api change with error-message?:

```tsx
function useMeasure(options: Options, ResizeObserver?: ResizeObserver) {
  const ResizeObserver =
    injectedResizeObserver ||
    (typeof window === "undefined"
      ? class ResizeObserver {}
      : (window as any).ResizeObserver);

  if (!ResizeObserver) {
    throw new Error(
      "This browser does not support `ResizeObserver` out of the box. Please provide a polyfill as a second argument to `useMeasure()`."
    );
  }
}
```

**Comment by drcmda** [comment]
looks good

**Comment by drcmda** [comment]
though, why would anyone want to inject one? is that how it's normally done? must admit the concept of a "ponyfil" is new to me. i only ever knew about just importing a polyfil which either detects a native impl or overwrites window.xyz.

**Comment by donysukardi** [comment]
@drcmda i suppose it’s such that the behaviours are more _predictable_ and uniform in all browsers. Coz likely you’d be testing on browsers that support the feature more. I personally don’t see much advantage either.

**Comment by everweij** [comment]
Yes, the extra parameter is more for extra flexibility (user can patch global, or pass the polyfill as argument), and for the folks who at no circumstance want to alter the window object.
If have no problems if you guys want to skip the injection thing ;)

**Comment by drcmda** [comment]
to me it's fine. i was just curious. would you merge it like that? we could cut a release then.

**Comment by drcmda** [comment]
thanks everyone!
